//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen_P5_Bram.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Examen_P5_Bram.Translations.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string A_AccountPassword {
            get {
                return ResourceManager.GetString("A_AccountPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string A_BackToList {
            get {
                return ResourceManager.GetString("A_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string A_CreateNew {
            get {
                return ResourceManager.GetString("A_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string A_Delete {
            get {
                return ResourceManager.GetString("A_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string A_DeleteConfirm {
            get {
                return ResourceManager.GetString("A_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string A_Description {
            get {
                return ResourceManager.GetString("A_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string A_Details {
            get {
                return ResourceManager.GetString("A_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string A_Edit {
            get {
                return ResourceManager.GetString("A_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string A_Email {
            get {
                return ResourceManager.GetString("A_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmed ?.
        /// </summary>
        public static string A_EmailConfirmed {
            get {
                return ResourceManager.GetString("A_EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a correct email address.
        /// </summary>
        public static string A_EmailError {
            get {
                return ResourceManager.GetString("A_EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string A_FirstName {
            get {
                return ResourceManager.GetString("A_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello .
        /// </summary>
        public static string A_Hello {
            get {
                return ResourceManager.GetString("A_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string A_Index {
            get {
                return ResourceManager.GetString("A_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string A_Language {
            get {
                return ResourceManager.GetString("A_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string A_LastName {
            get {
                return ResourceManager.GetString("A_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave without saving.
        /// </summary>
        public static string A_Leave {
            get {
                return ResourceManager.GetString("A_Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string A_Login {
            get {
                return ResourceManager.GetString("A_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logoff.
        /// </summary>
        public static string A_Logoff {
            get {
                return ResourceManager.GetString("A_Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string A_Name {
            get {
                return ResourceManager.GetString("A_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string A_PhoneNumber {
            get {
                return ResourceManager.GetString("A_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number confirmed ?.
        /// </summary>
        public static string A_PhoneNumberConfirmed {
            get {
                return ResourceManager.GetString("A_PhoneNumberConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string A_Product {
            get {
                return ResourceManager.GetString("A_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string A_Register {
            get {
                return ResourceManager.GetString("A_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to enter a {0}.
        /// </summary>
        public static string A_Required {
            get {
                return ResourceManager.GetString("A_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string A_Save {
            get {
                return ResourceManager.GetString("A_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account..
        /// </summary>
        public static string AccountCreate {
            get {
                return ResourceManager.GetString("AccountCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string AccountEmail {
            get {
                return ResourceManager.GetString("AccountEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string AccountPassword {
            get {
                return ResourceManager.GetString("AccountPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your password.
        /// </summary>
        public static string AccountPasswordConfirmation {
            get {
                return ResourceManager.GetString("AccountPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and its confirmation don&apos;t match.
        /// </summary>
        public static string AccountPasswordConfirmationError {
            get {
                return ResourceManager.GetString("AccountPasswordConfirmationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must have at least  {2} characters and should not be longer than {1} characters..
        /// </summary>
        public static string AccountPasswordError {
            get {
                return ResourceManager.GetString("AccountPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string AccountRememberMe {
            get {
                return ResourceManager.GetString("AccountRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string AccountUserName {
            get {
                return ResourceManager.GetString("AccountUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must have at least  {2} characters and should not be longer than {1} characters..
        /// </summary>
        public static string AccountUserNameError {
            get {
                return ResourceManager.GetString("AccountUserNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight.
        /// </summary>
        public static string B_Flight {
            get {
                return ResourceManager.GetString("B_Flight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string B_Name {
            get {
                return ResourceManager.GetString("B_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        public static string Click {
            get {
                return ResourceManager.GetString("Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plane.
        /// </summary>
        public static string F_Airplane {
            get {
                return ResourceManager.GetString("F_Airplane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departing Airport.
        /// </summary>
        public static string F_AirportFrom {
            get {
                return ResourceManager.GetString("F_AirportFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival Airport.
        /// </summary>
        public static string F_AirportTo {
            get {
                return ResourceManager.GetString("F_AirportTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string HomeAbout {
            get {
                return ResourceManager.GetString("HomeAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string HomeAdministration {
            get {
                return ResourceManager.GetString("HomeAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examen Programmeren 5.
        /// </summary>
        public static string HomeAppName {
            get {
                return ResourceManager.GetString("HomeAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking.
        /// </summary>
        public static string HomeBooking {
            get {
                return ResourceManager.GetString("HomeBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string HomeContact {
            get {
                return ResourceManager.GetString("HomeContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flights.
        /// </summary>
        public static string HomeFlight {
            get {
                return ResourceManager.GetString("HomeFlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string HomeLogin {
            get {
                return ResourceManager.GetString("HomeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logoff.
        /// </summary>
        public static string HomeLogoff {
            get {
                return ResourceManager.GetString("HomeLogoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string HomeManagement {
            get {
                return ResourceManager.GetString("HomeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string HomeRegister {
            get {
                return ResourceManager.GetString("HomeRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string HomeServices {
            get {
                return ResourceManager.GetString("HomeServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book your next flight.
        /// </summary>
        public static string HomeText {
            get {
                return ResourceManager.GetString("HomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Booking.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string HomeUsers {
            get {
                return ResourceManager.GetString("HomeUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account..
        /// </summary>
        public static string RegisterCreateAccount {
            get {
                return ResourceManager.GetString("RegisterCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Login Fails.
        /// </summary>
        public static string User_AccessFailedCount {
            get {
                return ResourceManager.GetString("User_AccessFailedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock out enabled ?.
        /// </summary>
        public static string User_LockoutEnabled {
            get {
                return ResourceManager.GetString("User_LockoutEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock out end date (utc).
        /// </summary>
        public static string User_LockoutEndDateUtc {
            get {
                return ResourceManager.GetString("User_LockoutEndDateUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset PW.
        /// </summary>
        public static string User_ResetPassword {
            get {
                return ResourceManager.GetString("User_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two factor login enabled ?.
        /// </summary>
        public static string User_TwoFactorEnabled {
            get {
                return ResourceManager.GetString("User_TwoFactorEnabled", resourceCulture);
            }
        }
    }
}
